domain: #domain
consul:
  replicas: 1
couchdb:
  image:
    tag: 2.3.1
  replicas: 1
  persistence: true
  adminParty: true
  couchdbConfig:
    couchdb:
      uuid: 502f5f7d-05f0-42ac-befa-7c5567387594