apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: {{ include "streampipes.fullname" . }}-backend
  name: {{ include "streampipes.fullname" . }}-backend
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Mi
