apiVersion: v1
kind: Service
metadata:
  name: streampipes-ui
  labels:
    {{- include "streampipes.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "streampipes.selectorLabels-ui" . | nindent 4 }}
